services:
  splunk:
    image: "splunk/splunk:10.4"
    container_name: splunk-jinja2-formatter
    entrypoint: ["/bin/bash", "-c", "if [ -f /opt/splunk/bin/mongod-7.0 ]; then sudo ln -sf /opt/splunk/bin/mongod-7.0 /opt/splunk/bin/mongod-8.0; fi; exec /sbin/entrypoint.sh \"$@\"", "--"]
    command: ["start-service"]
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_PASSWORD=changed!
      - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
    ports:
      - "8000:8000"
      - "8088:8088"
      - "8089:8089"

    healthcheck:
      test: ["CMD", "/sbin/checkstate.sh"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s
