[project]
name = "splunk-jinja-formatter"
version = "1.0.6"
description = "A Splunk custom search command to format events using Jinja2 templates"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "jinja2>=3.1.5",
    "pyyaml>=6.0.2",
    "splunk-sdk>=2.1.0,<3.0.0",
]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
]
